name: KICS PR comment

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run kics Scan
      uses: checkmarx/kics-github-action@v1.4
      with:
         path: "./"
         output_path: myResults/
         fail_on: high,medium
         ignore_on_exit: results
         enable_comments: true
   
