# This is a basic workflow to help you get started with Actions

name: KICS

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  kics-scan:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.event.pull_request.head.sha }}

      # Runs a single command using the runners shell
      - name: runs KICS scan
        uses: checkmarx/kics-action@v1.4
        with:
           path: "./,terraform/aws"
           fail_on: high,medium
           output_path: myResults/
      - name: display kics results
        run: |
          cat myResults/results.json
