name: PR-Diff

on:
  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7

      - name: List all changed files
        run: |
          files_to_scan = ""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
            files_to_scan = $files_to_scan.",".$file
          done
          echo $files_to_scan
